name: Build release, deploy it on prod env, and publish
# push tag to trigger this action
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
#  TODO build_release_and_deploy_prod:

  publish_release:
#    needs: build_release_and_deploy_prod
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
