name: test
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: read

jobs:
  test1:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test variable
        run : |
          echo " event_name = ${{github.event_name}}"
          echo " ref = ${{github.ref}}"
          echo " ${{RELEASE_NAME}}" 
          echo " ref_name = ${{github.ref_name}}"
          echo " repository_owner = ${{github.repository_owner}}"
          echo " repository_owner_id = ${{github.repository_owner_id}}"

  test2:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: test_action
        run : echo "test action = ${{ github.event_name}}"

  test3:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout2
        uses: actions/checkout@v4
      - name: test_action2
        run : |
          echo "test action = ${{ github.event_name}}"
          echo "runner.name = ${{runner.name}}"
          echo "runner.os = ${{runner.os}}"

  test4:
    runs-on: ubuntu-latest
    if: ${{RELEASE_NAME}} =''
    steps:
      - name: Checkout2
        uses: actions/checkout@v4
      - name: test_action2
        run : |
          echo "test action = ${{ github.event_name}}"
          echo "runner.name = ${{runner.name}}"
          echo "runner.os = ${{runner.os}}"