name: test_appel_out
on:
  workflow_call:
    intput:
      RELEASE_NAME:
        required: false
        type: string

permissions:
  contents: read

jobs:
  test1:
    if: ${{ inputs.RELEASE_NAME != '' }} || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test variable
        run : |
          echo " event_name = ${{github.event_name}}"
          echo " ref = ${{github.ref}}"
          echo " ref_name = ${{github.ref_name}}"
          echo " repository_owner = ${{github.repository_owner}}"
          echo " repository_owner_id = ${{github.repository_owner_id}}"

  test2:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: test_action
        run : echo "test action = ${{ github.event_name}}"

  test3:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout2
        uses: actions/checkout@v4
      - name: test_action2
        run : |
          echo "test action = ${{ github.event_name}}"
          echo "runner.name = ${{runner.name}}"
          echo "runner.os = ${{runner.os}}"

  test4:
    runs-on: ubuntu-latest
    if: ${{RELEASE_NAME}} =''
    steps:
      - name: Checkout2
        uses: actions/checkout@v4
      - name: test_action2
        run : |
          echo "test action = ${{ github.event_name}}"
          echo "runner.name = ${{runner.name}}"
          echo "runner.os = ${{runner.os}}"