name: test_appel
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  deploy_prod:
    uses: ./.github/workflows/test.yml
    with:
      RELEASE_NAME: ${{ github.ref_name }}


