name: verif_alter
on:
  push:
    branches:
      - main
    paths:
      - db/alter/*.sh
env:
  MA_VAR_TEST: variable test
jobs:
  verif_alter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          echo " fin job $MA_VAR_TEST"
          echo " fin job ${{ env.MA_VAR_TEST }}"
          echo " fin job $GITHUB_REF"
          echo " fin job ${{ github.ref }}"
  deploy:
    runs-on: ubuntu-latest
    needs: verif_alter
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          ls db/alter/*.sh

