name: verif_alter
on:
  push:
    branches:
      - main
    paths:
      - db/alter/*.sh
jobs:
  verif_alter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          ls db/alter/*.sh
          echo "${{ github.event.before }} -- ${{ github.sha }} "
          echo "${{ toJSON(github.event) }}"

  deploy:
    needs: verif_alter
    runs-on: ubuntu-latest
    steps:
      - name: deployer script
        run : |
          echo " action = ${{github}}"
