name: verif_alter
on:
  push:
    branches:
      - main
    paths:
      - db/alter/*.sh
jobs:
  verif_alter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          echo  "${{ github.event.before }}..${{ github.sha }}"
          echo "${{ toJSON(github.event) }}"
          echo " fin job 1"
#          git diff --name-only HEAD^ HEAD
  deploy:
    runs-on: ubuntu-latest
    needs: verif_alter
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          ls db/alter/*.sh

