name: verif_alter
on:
  push:
    branches:
      - main
    paths:
      - db/alter/*.sh
jobs:
  verif_alter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          git diff --name-only ${{ github.event.before }}..${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: verif_alter
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          ls db/alter/*.sh
          echo "${{ toJSON(github.event) }}"
