name: verif_alter
on:
  push:
    branches:
      - main
    paths:
      - db/alter/*.sh
jobs:
  verif_alter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          git diff --name-only caae6c04086c37ed85bd9c8f477f9f76253650f7..ba15f667fa8e967e32090a77004fff38fb886c38 

  deploy:
    runs-on: ubuntu-latest
    needs: verif_alter
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          ls db/alter/*.sh
          echo "${{ toJSON(github.event) }}"
          git diff --name-only ${{ github.event.before }}..${{ github.sha }}
