name: verif_alter
on:
  push:
    branches:
      - main
    paths:
      - db/alter/*.sh
jobs:
  verif_alter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: copy_alter
        run : |
          ls db/alter/*.sh
          echo " event_name = ${{github.event_name}}"
          echo " ref = ${{github.ref}}"
          echo " ref_name = ${{github.ref_name}}"
          echo " repository_owner = ${{github.repository_owner}}"
          echo " repository_owner_id = ${{github.repository_owner_id}}"         

  deploy:
    needs: verif_alter
    runs-on: ubuntu-latest
    steps:
      - name: deployer script
        run : |
          echo " action = ${{github}}"
